{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-coverage-proto",
    "version": "30.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.2.0.jar",
          "url": "android-test-plugin-host-coverage-proto-30.2.0.jar",
          "size": 23204,
          "sha512": "4a78a717d921994fe836e8cc8eb406eeabc22c8e5482eb70b06b3c6742a58116173e37468fa2548d9f594ecd0eff57aee4ffb17aa601b339a5e176c6df4c3274",
          "sha256": "387122afdcf1da31ad1b3b2b63ce08279a57ea23c42b417d0df144deb11a091f",
          "sha1": "5bb08dce324a988938774acd2ffc2c8761ba8bb2",
          "md5": "fd84a419b25b29f276c66d0d52754f11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.2.0.jar",
          "url": "android-test-plugin-host-coverage-proto-30.2.0.jar",
          "size": 23204,
          "sha512": "4a78a717d921994fe836e8cc8eb406eeabc22c8e5482eb70b06b3c6742a58116173e37468fa2548d9f594ecd0eff57aee4ffb17aa601b339a5e176c6df4c3274",
          "sha256": "387122afdcf1da31ad1b3b2b63ce08279a57ea23c42b417d0df144deb11a091f",
          "sha1": "5bb08dce324a988938774acd2ffc2c8761ba8bb2",
          "md5": "fd84a419b25b29f276c66d0d52754f11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.2.0-javadoc.jar",
          "url": "android-test-plugin-host-coverage-proto-30.2.0-javadoc.jar",
          "size": 425611,
          "sha512": "c99d2e5efb794000088b0289ef388521ab9a4b12890281497af63a25659f5a9172ddc0d6784483af09602abf02f565bca4ba454f7be2844ad8318f56c13a1d88",
          "sha256": "818bde064001a9b2164e6ac601fc823b8b3eadebfe876cbffd3d1db435b51fcf",
          "sha1": "bf6abf1d7641f8e004f2a898f2c6b681c5cf90c3",
          "md5": "44d07ee064ab3f32b8c24ec6a42d3ec3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-coverage-proto-30.2.0-sources.jar",
          "url": "android-test-plugin-host-coverage-proto-30.2.0-sources.jar",
          "size": 11274,
          "sha512": "52922f7e25a5313c5487b10941acd33faab627d6c8748768488de01ea0105c0ec39fd4e5918eaeb995f8a59b4695ec68e9a9b44556b8dadd4d0c45c9950e1805",
          "sha256": "5d2bda1a62713b298949d8d4efeaaac0667840db620aabf3b3e3293642962eac",
          "sha1": "75a4540913f9d7964bc38560f495a1bf172f9bb1",
          "md5": "25df7a4a92b8dd56b105c99e13d5546d"
        }
      ]
    }
  ]
}
